[phases.setup]
nixPkgs = ['nodejs_22', 'bun', 'openssl']

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = [
  'cd packages/soul-engine-cloud && bun install',
  'cd packages/soul-engine-cloud && bun run prisma:generate'
]

[start]
cmd = 'cd packages/soul-engine-cloud && bun ./scripts/run-server.ts'
